name: Kish Sub Aqua Club
markdown: redcarpet
highlighter: rouge
exclude:
  - vendor

gallery:
  videos:
    - name: U260, Cork
      embed: ae0djwb_avE
    - name: Connemara, Galway
      embed: VGcxEqWekPY
    - name: Dunfanaghy, Donegal
      embed: WVKXAUprbUs
    - name: Sandycove, Dublin
      embed: GJWFquaxGk8
    - name: Schull, Cork
      embed: y3zAQ4HYgrU
